name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  build:
    name: Package AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf boris.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "boris.war"
        target: "/opt/tomcat/webapps"

  deploy:
    name: SAV IPFS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf fichier.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier war sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add fichier.war
        shell: alpine.sh --root {0}

  mySQL_Save:
        name: SAV MYSQL DB
        runs-on: ubuntu-latest
        needs: build
        steps:
          - uses: actions/checkout@master
          - run: |
              jar cvf fichier.war *
          - uses: jirutka/setup-alpine@v1
            with:
              branch: v3.15
          - run: |
              apk add go-ipfs
              ipfs init
              ipfs daemon &
            shell: alpine.sh --root {0}
          - name: Sauvegarde DB MySQL
            run: |
              apk add mysql mysql-client
              ssh -i ${{ secrets.EC2_SSH_KEY }} admin@ec2-13-39-79-82.eu-west-3.compute.amazonaws.com -fN -L 0.0.0.0:3307:127.0.0.1:3306
              mysqldump -ucnam -P3307 -p${{ secrets.MYSQLDUMP_PASSWORD}} films > sauvegarde_films.sql
            shell: alpine.sh --root {0}
  
